<a href="https://colab.research.google.com/github/taufiqhidayatulloh/machine-learning/blob/main/feature_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

implementasi normalisasi

In [2]:
def norm_data(data):
  '''
  Melakukan normalisasi data.

  Parameters:
    data (list) : Data yang akan dinormalisasi

  Returns:
    data (list) : Data hasil normalisasi
  '''

  data_max = max(data)
  data_min = min(data)
  data_len = len(data)

  for i in range(0, data_len):
    data[i] = (data[i] - data_min) / (data_max-data_min)

  return data

# Contoh
data = [10, 11, 12, 14, 16]
n_data = norm_data(data)
print(n_data)

[0.0, 0.16666666666666666, 0.3333333333333333, 0.6666666666666666, 1.0]


implementasi normalisasi dengan
menggunakan library Scikit-learn untuk kasus data fitur dalam bentuk 2 dimensi

In [7]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

np.set_printoptions(precision=6) #pembulatan 4 angka koma
np.set_printoptions(suppress=True) #hilangkan nilai e

data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

data = np.asarray(data)
print('Data Asli')
print(data)

scaler = MinMaxScaler()

scaled = scaler.fit_transform(data)
print('Data Ternormalisasi')
print(scaled)



Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Ternormalisasi
[[1.       0.      ]
 [0.285714 1.      ]
 [0.       0.058116]]


Implementasi Ordinal Encoding

In [8]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

transform_oe = oe.fit_transform(data)

print('Data Asli')
print(data)

print('Data Transformasi Ordinal Encoder')
print(transform_oe)

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi Ordinal Encoder
[[2.]
 [0.]
 [1.]
 [3.]]


Implementasi One-Hot Encoding

In [10]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

transform_ohe = ohe.fit_transform(data)

print('Data Asli')
print(data)

print('Data Transformasi One Hot Encoding')
print(transform_ohe.toarray())

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi One Hot Encoding
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


Implementasi Dummy Variable Encoding

In [11]:
from sklearn.preprocessing import OneHotEncoder

de = OneHotEncoder(drop='first')

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

transform_de = de.fit_transform(data)

print('Data Asli')
print(data)

print('Data Transformasi One Hot Encoding')
print(transform_de.toarray())

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi One Hot Encoding
[[0. 1. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


Studi Kasus Ekstrasi Fitur dari Data Teks

In [12]:
corpus = ['the house had a tiny little mouse',
          'the cat saw the mouse',
          'the mouse ran away from the house',
          'the cat finally ate the house',
          'the end of the mouse story']



In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

vect = TfidfVectorizer(stop_words='english')

resp = vect.fit_transform(corpus)

print(resp)

  (0, 7)	0.33875373403393194
  (0, 6)	0.6012854497921586
  (0, 11)	0.6012854497921586
  (0, 5)	0.4026878734386609
  (1, 9)	0.7127752157729959
  (1, 2)	0.5750625560879445
  (1, 7)	0.4015651234424611
  (2, 1)	0.6012854497921586
  (2, 8)	0.6012854497921586
  (2, 7)	0.338753734033932
  (2, 5)	0.40268787343866097
  (3, 0)	0.5680140774328015
  (3, 4)	0.5680140774328015
  (3, 2)	0.45827018116532225
  (3, 5)	0.38040564760664297
  (4, 10)	0.6569003716341058
  (4, 3)	0.6569003716341058
  (4, 7)	0.3700862108940939


In [16]:
vect.get_feature_names_out()

array(['ate', 'away', 'cat', 'end', 'finally', 'house', 'little', 'mouse',
       'ran', 'saw', 'story', 'tiny'], dtype=object)

In [18]:
corpus = ['the house had a tiny little mouse',
          'the cat saw the mouse',
          'the mouse ran away from the house',
          'the cat finally ate the house',
          'the end of the mouse story']

from sklearn.feature_extraction.text import TfidfVectorizer

vect = TfidfVectorizer(stop_words='english')

resp = vect.fit_transform(corpus)

print('Hasil TF-IDF')
print(resp)

print('Hasil Token')
print(vect.get_feature_names_out())

Hasil TF-IDF
  (0, 7)	0.33875373403393194
  (0, 6)	0.6012854497921586
  (0, 11)	0.6012854497921586
  (0, 5)	0.4026878734386609
  (1, 9)	0.7127752157729959
  (1, 2)	0.5750625560879445
  (1, 7)	0.4015651234424611
  (2, 1)	0.6012854497921586
  (2, 8)	0.6012854497921586
  (2, 7)	0.338753734033932
  (2, 5)	0.40268787343866097
  (3, 0)	0.5680140774328015
  (3, 4)	0.5680140774328015
  (3, 2)	0.45827018116532225
  (3, 5)	0.38040564760664297
  (4, 10)	0.6569003716341058
  (4, 3)	0.6569003716341058
  (4, 7)	0.3700862108940939
Hasil Token
['ate' 'away' 'cat' 'end' 'finally' 'house' 'little' 'mouse' 'ran' 'saw'
 'story' 'tiny']
